version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
    environment:
      - FLASK_APP=src/app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/seekin_demo
      - NOTION_TOKEN=${NOTION_TOKEN}
      - NOTION_PAGE_ID=${NOTION_PAGE_ID}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - PYTHONPATH=/app
    depends_on:
      - db
    command: python3 src/app.py

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=seekin_demo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: 