version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./src:/app/src
    environment:
      - FLASK_APP=src/app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/seekin_demo
      - NOTION_TOKEN=${NOTION_TOKEN}
      - NOTION_PAGE_ID=${NOTION_PAGE_ID}
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=seekin_demo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: 