version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./src:/app/src
    environment:
      - FLASK_APP=src/app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/seekin_demo
      - NOTION_TOKEN=${NOTION_TOKEN}
      - NOTION_PAGE_ID=${NOTION_PAGE_ID}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - PYTHONPATH=/app
    command: python3 src/app.py